services:
  structurizr-lite:
    image: structurizr/lite:latest
    container_name: structurizr-lite
    ports:
      - 8080:8080
    volumes:
      - ./architecture:/usr/local/structurizr
    restart: unless-stopped
